### ISSUE TITLE
Static Method Definition

### ISSUE THREAD

**Issue by jtzupan** [NapsterInBlue/notes#12]
[This](https://napsterinblue.github.io/notes/python/oop/method_decorators/) may be technically correct, but I have always learned the key feature of a @staticmethod is that it is not bound to the method or class and therefore cannot modify the class, but is related to the class i.e. it is a loosely related function not dependent on the class or instance variables.  I guess in a roundabout way saying that it can run without the instance being instantiated maybe gets you to the same spot, but I think a little further clarification would be helpful.

Take this feedback however you want, but it might be useful to expand your explanation/definition a little bit.

Sources:
[source1](https://www.pythoncentral.io/difference-between-staticmethod-and-classmethod-in-python/)
[source2](https://www.geeksforgeeks.org/class-method-vs-static-method-python/)

**Comment by NapsterInBlue** [comment]
Are you cool with this attribution? Link goes to your GitHub profile.

![image](https://user-images.githubusercontent.com/3505365/42002685-2225db06-7a36-11e8-9869-0c9a5cabcf42.png)

**Comment by jtzupan** [comment]
Yes, this looks good.
